// Code generated by go generate; DO NOT EDIT.
package example

import (
	"context"
	"log"
)

type TestInterfaceWrapper struct {
	inner TestInterface
}

func NewTestInterfaceWrapper(inner TestInterface) TestInterface {
	return &TestInterfaceWrapper{
		inner: inner,
	}
}

func (w *TestInterfaceWrapper) TestMethod(
	ctx context.Context, slice []int64, testMap map[string]context.Context, points ...string) (
	[]string, error) {
	// Start of customize code

	log.Println("Custom code here")

	// End of customize code

	return w.inner.TestMethod(ctx, slice, testMap, points...)
}

func (w *TestInterfaceWrapper) TestMethod2(
	ctx context.Context) error {
	// Start of customize code

	log.Println("Custom code here")

	// End of customize code

	return w.inner.TestMethod2(ctx)
}
